name: "CI"

on:
  push:
    branches:
      - main

concurrency: docs

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@v4
    - name: Run the Magic Nix Cache
      uses: DeterminateSystems/magic-nix-cache-action@v1
    - name: Build docs
      run: |
        nix build -L .#loadbench-doc
        mkdir docs
        cp -r result/target/doc/* ./docs
        echo "<meta http-equiv=\"refresh\" content=\"0; url=loadbench\">" > docs/index.html
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs
